version: "3.9"
services:
  api:
    image: api:latest
    depends_on:
      - identityserver
    entrypoint: /bin/sh -c "chmod -R 755 /usr/local/share/ca-certificates && dotnet Api.dll"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:7001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/usr/local/share/ca-certificates/pymath-cert.pfx
      - AUTHENTICATION__AUTHORITY=https://localhost:7000
      - AUTHENTICATION__AUDIENCE=0d6a9f62-a1df-4689-be0d-d03d0d859a04
    ports:
      - "7001:7001"
    volumes:
      - ./idserver-ca/pymath-cert.pfx:/usr/local/share/ca-certificates/pymath-cert.pfx
      - api-keys:/root/.aspnet/DataProtection-Keys
  db:
    environment:
      - POSTGRES_PASSWORD=password
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  identityserver:
    image: identityserver:latest
    depends_on: 
      - db
    entrypoint: /bin/sh -c "chmod -R 755 /usr/local/share/ca-certificates && dotnet IdentityServer.dll"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:7000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/usr/local/share/ca-certificates/pymath-cert.pfx
      - CONNECTIONSTRINGS__IDENTITY=Server=db;Port=5432;Database=Identity;User Id=postgres;Password=password;
      - CONNECTIONSTRINGS__IDENTITYSERVER=Server=db;Port=5432;Database=IdentityServer;User Id=postgres;Password=password;
    ports:
      - "7000:7000"
    volumes:
      - ./idserver-ca/pymath-cert.pfx:/usr/local/share/ca-certificates/pymath-cert.pfx
      - identityserver-keys:/root/.aspnet/DataProtection-Keys
volumes: 
  db:
  identityserver-keys:
  api-keys:
    