version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: ./Api/Dockerfile
    depends_on:
      - identityserver
#    entrypoint: /bin/sh -c "update-ca-certificates && dotnet Apis.dll"
    environment:
      - ASPMETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:7001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/localhost.pfx
      - AUTHENTICATION__AUTHORITY=https://identityserver:7000
      - AUTHENTICATION__AUDIENCE=3218efc2-a865-4ce6-896c-e5c3449bd11e
    ports:
      - "7001:7001"
    volumes:
      - ./localhost.pfx:/https/localhost.pfx:ro
      - ./localhost.crt:/usr/local/share/ca-certificates/localhost:ro
      - api-keys:/root/.aspnet/DataProtection-Keys
  db:
    environment:
      - POSTGRES_PASSWORD=password
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  identityserver:
    build:
      context: .
      dockerfile: ./IdentityServer/Dockerfile
    depends_on: 
      - db
#    entrypoint: /bin/sh -c "update-ca-certificates && dotnets IdentityServers.dll"
    environment:
      - ASPMETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:7000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/localhost.pfx
      - CONNECTIONSTRINGS__IDENTITY=Server=db;Port=5432;Database=Identity;User Id=postgres;Password=password;
      - CONNECTIONSTRINGS__IDENTITYSERVER=Server=db;Port=5432;Database=IdentityServer;User Id=postgres;Password=password;
    ports:
      - "7000:7000"
    volumes:
      - ./localhost.pfx:/https/localhost.pfx:ro
      - ./localhost.crt:/usr/local/share/ca-certificates/localhost:ro
      - identityserver-keys:/root/.aspnet/DataProtection-Keys
volumes: 
  db:
  identityserver-keys:
  api-keys:
    